import Foundation

// MARK: - Reviews

enum MockReviews {
    static let set1: [SpotlyReview] = [
        SpotlyReview(id: "r1", authorName: "Chiedza Mutasa", authorInitials: "CM", rating: 5.0, comment: "Excellent service, easy booking, and a polished experience from start to finish.", date: Date().addingTimeInterval(-86400 * 3), verified: true, helpfulCount: 12),
        SpotlyReview(id: "r2", authorName: "Takudzwa Banda", authorInitials: "TB", rating: 4.5, comment: "Great atmosphere and reliable staff. Exactly the kind of place I would book again.", date: Date().addingTimeInterval(-86400 * 7), verified: true, helpfulCount: 8),
        SpotlyReview(id: "r3", authorName: "Rutendo Chigamba", authorInitials: "RC", rating: 4.0, comment: "Smooth experience overall. The listing details matched what I found on arrival.", date: Date().addingTimeInterval(-86400 * 14), verified: false, helpfulCount: 4)
    ]

    static let set2: [SpotlyReview] = [
        SpotlyReview(id: "r4", authorName: "Farai Ncube", authorInitials: "FN", rating: 5.0, comment: "Clean, professional, and well run. Spotly made it easy to choose the right option.", date: Date().addingTimeInterval(-86400 * 2), verified: true, helpfulCount: 15),
        SpotlyReview(id: "r5", authorName: "Nyasha Dube", authorInitials: "ND", rating: 4.5, comment: "The team was responsive and the service felt premium without being complicated.", date: Date().addingTimeInterval(-86400 * 5), verified: true, helpfulCount: 9)
    ]
}

// MARK: - Services and products

enum MockServices {
    static let restaurantMenu: [SpotlyService] = [
        SpotlyService(id: "food1", name: "Signature plate", description: "House favourite prepared fresh to order", duration: 25, price: 12, currency: "USD", category: "Popular"),
        SpotlyService(id: "food2", name: "Chef's table reservation", description: "A polished dinner booking for two or four guests", duration: 90, price: 0, currency: "USD", category: "Reservation"),
        SpotlyService(id: "food3", name: "Family platter", description: "Shared mains, sides, and drinks for a group", duration: 35, price: 38, currency: "USD", category: "Combos")
    ]

    static let groceryItems: [SpotlyService] = [
        SpotlyService(id: "g1", name: "Fresh avocados", description: "Seasonal local avocados", duration: 0, price: 4, currency: "USD", category: "Fresh produce"),
        SpotlyService(id: "g2", name: "Bread", description: "Fresh bakery loaf", duration: 0, price: 2, currency: "USD", category: "Bakery"),
        SpotlyService(id: "g3", name: "Milk", description: "2 litre dairy milk", duration: 0, price: 3, currency: "USD", category: "Dairy"),
        SpotlyService(id: "g4", name: "Eggs", description: "Tray of free range eggs", duration: 0, price: 5, currency: "USD", category: "Dairy"),
        SpotlyService(id: "g5", name: "Chicken", description: "Fresh whole chicken", duration: 0, price: 8, currency: "USD", category: "Butchery"),
        SpotlyService(id: "g6", name: "Rice", description: "Long grain rice pack", duration: 0, price: 7, currency: "USD", category: "Pantry"),
        SpotlyService(id: "g7", name: "Tomatoes", description: "Fresh tomato punnet", duration: 0, price: 3, currency: "USD", category: "Fresh produce"),
        SpotlyService(id: "g8", name: "Bottled water", description: "6 pack still water", duration: 0, price: 4, currency: "USD", category: "Drinks"),
        SpotlyService(id: "g9", name: "Household essentials", description: "Cleaning and paper basics", duration: 0, price: 10, currency: "USD", category: "Home")
    ]

    static let pharmacyItems: [SpotlyService] = [
        SpotlyService(id: "p1", name: "Health consultation", description: "In-store pharmacist guidance for general wellness items", duration: 15, price: 0, currency: "USD", category: "Service"),
        SpotlyService(id: "p2", name: "First aid essentials", description: "Bandages, antiseptic, and basic care items", duration: 0, price: 12, currency: "USD", category: "Shop"),
        SpotlyService(id: "p3", name: "Prescription verification", description: "Prescription items require in-store verification before collection", duration: 10, price: 0, currency: "USD", category: "Regulated")
    ]

    static let doctorServices: [SpotlyService] = [
        SpotlyService(id: "d1", name: "General consultation", description: "Appointment with a family doctor", duration: 30, price: 35, currency: "USD", category: "Consultation"),
        SpotlyService(id: "d2", name: "Follow-up appointment", description: "Review visit for existing patients", duration: 20, price: 25, currency: "USD", category: "Consultation"),
        SpotlyService(id: "d3", name: "Wellness check", description: "Routine health screening appointment", duration: 45, price: 45, currency: "USD", category: "Screening")
    ]

    static let flowerGiftItems: [SpotlyService] = [
        SpotlyService(id: "fg1", name: "Rose bouquet", description: "Fresh rose arrangement with wrapping", duration: 0, price: 28, currency: "USD", category: "Flowers"),
        SpotlyService(id: "fg2", name: "Birthday gift box", description: "Curated treats, card, and keepsake", duration: 0, price: 35, currency: "USD", category: "Gifts"),
        SpotlyService(id: "fg3", name: "Celebration hamper", description: "Premium hamper for birthdays and milestones", duration: 0, price: 55, currency: "USD", category: "Hampers"),
        SpotlyService(id: "fg4", name: "Sympathy flowers", description: "Simple respectful arrangement", duration: 0, price: 30, currency: "USD", category: "Flowers"),
        SpotlyService(id: "fg5", name: "Custom arrangement", description: "Florist-designed arrangement by request", duration: 0, price: 45, currency: "USD", category: "Custom")
    ]

    static let beautyServices: [SpotlyService] = [
        SpotlyService(id: "bty1", name: "Haircut", description: "Cut, wash, and finish", duration: 45, price: 20, currency: "USD", category: "Hair"),
        SpotlyService(id: "bty2", name: "Braids", description: "Protective styling consultation and braiding", duration: 180, price: 45, currency: "USD", category: "Hair"),
        SpotlyService(id: "bty3", name: "Manicure", description: "Classic manicure with polish", duration: 45, price: 18, currency: "USD", category: "Nails"),
        SpotlyService(id: "bty4", name: "Facial", description: "Hydrating facial treatment", duration: 60, price: 35, currency: "USD", category: "Skin")
    ]

    static let spaServices: [SpotlyService] = [
        SpotlyService(id: "spa1", name: "Swedish massage", description: "Full-body relaxation massage", duration: 60, price: 45, currency: "USD", category: "Massage"),
        SpotlyService(id: "spa2", name: "Deep tissue massage", description: "Focused pressure for tight muscles", duration: 75, price: 55, currency: "USD", category: "Massage"),
        SpotlyService(id: "spa3", name: "Spa day package", description: "Massage, facial, and light refreshments", duration: 180, price: 110, currency: "USD", category: "Package")
    ]

    static let activityServices: [SpotlyService] = [
        SpotlyService(id: "act1", name: "Standard booking", description: "Reserve a slot for your group", duration: 90, price: 15, currency: "USD", category: "Activity"),
        SpotlyService(id: "act2", name: "Guided experience", description: "Hosted activity with a local guide", duration: 120, price: 25, currency: "USD", category: "Guided"),
        SpotlyService(id: "act3", name: "Group package", description: "Bundle for families or teams", duration: 180, price: 60, currency: "USD", category: "Package")
    ]

    static let staycationServices: [SpotlyService] = [
        SpotlyService(id: "st1", name: "Day pass", description: "Access to pool, gardens, and dining credit", duration: 480, price: 35, currency: "USD", category: "Day escape"),
        SpotlyService(id: "st2", name: "Weekend stay", description: "Two-night stay package for two", duration: 2880, price: 220, currency: "USD", category: "Stay"),
        SpotlyService(id: "st3", name: "Retreat package", description: "Accommodation with curated activities", duration: 2880, price: 260, currency: "USD", category: "Retreat")
    ]
}

// MARK: - Businesses

enum MockBusinesses {
    private static func make(
        id: String, name: String, tagline: String, description: String,
        categoryID: String, categoryName: String, location: SpotlyLocation,
        rating: Double, reviewCount: Int, priceLevel: Int, distance: String,
        gradientKey: String, status: BusinessStatus = .open, openingHours: String,
        phone: String? = nil, isVerified: Bool = true, isFeatured: Bool = false,
        imageNames: [String] = [], tags: [String], services: [SpotlyService],
        reviews: [SpotlyReview] = MockReviews.set1, highlights: [String]
    ) -> SpotlyBusiness {
        SpotlyBusiness(id: id, name: name, tagline: tagline, description: description, categoryID: categoryID, categoryName: categoryName, location: location, rating: rating, reviewCount: reviewCount, priceLevel: priceLevel, distance: distance, imageURLs: imageNames, gradientKey: gradientKey, status: status, openingHours: openingHours, phone: phone, isVerified: isVerified, isFeatured: isFeatured, tags: tags, services: services, reviews: reviews, highlights: highlights)
    }

    static let all: [SpotlyBusiness] = [
        make(id: "b001", name: "Namaste Harare", tagline: "Contemporary dining with a Zim soul", description: "A refined Borrowdale dining room blending international technique with Zimbabwean produce. Ideal for date nights, client dinners, and polished group plans.", categoryID: "restaurants", categoryName: "Restaurant", location: .borrowdale, rating: 4.8, reviewCount: 312, priceLevel: 3, distance: "1.2 km", gradientKey: "restaurants", openingHours: "Tue-Sun · 12:00-22:30", phone: "+263 77 200 0001", isFeatured: true, imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], tags: ["Fine dining", "Cocktails", "Date night"], services: MockServices.restaurantMenu, highlights: ["Reserve tables", "Private dining", "Verified partner"]),
        make(id: "b002", name: "The Braai House", tagline: "Fire-grilled plates and weekend energy", description: "A polished local braai spot for flame-grilled meats, sadza sides, salads, and casual group dinners.", categoryID: "restaurants", categoryName: "Restaurant", location: .avondale, rating: 4.6, reviewCount: 228, priceLevel: 2, distance: "1.8 km", gradientKey: "restaurants", openingHours: "Daily · 11:00-22:00", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_2"], tags: ["Braai", "Family", "Takeaway"], services: MockServices.restaurantMenu, highlights: ["Group tables", "Takeaway ready", "Local favourites"]),
        make(id: "b003", name: "Sakura Sushi", tagline: "Fresh sushi and modern Japanese plates", description: "A clean, compact sushi bar with platters, rice bowls, and fresh daily specials for dine-in or takeaway.", categoryID: "restaurants", categoryName: "Restaurant", location: .samLevys, rating: 4.7, reviewCount: 176, priceLevel: 3, distance: "3.0 km", gradientKey: "restaurants", openingHours: "Mon-Sat · 12:00-21:30", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], tags: ["Sushi", "Bowls", "Takeaway"], services: MockServices.restaurantMenu, highlights: ["Fresh platters", "Lunch specials", "Verified partner"]),
        make(id: "b004", name: "Victoria 22", tagline: "Classic Harare dining", description: "Elegant dining in a landmark Harare setting with attentive service and a menu built for special occasions.", categoryID: "restaurants", categoryName: "Restaurant", location: .harare, rating: 4.8, reviewCount: 344, priceLevel: 4, distance: "4.2 km", gradientKey: "restaurants", openingHours: "Tue-Sun · 18:00-22:00", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_2"], tags: ["Fine dining", "Celebrations"], services: MockServices.restaurantMenu, highlights: ["Occasion dining", "Wine list", "Reservations"]),
        make(id: "b005", name: "Amanzi", tagline: "Garden dining and relaxed luxury", description: "A refined garden restaurant known for calm service, polished plates, and long lunches in the north of Harare.", categoryID: "restaurants", categoryName: "Restaurant", location: .borrowdale, rating: 4.7, reviewCount: 401, priceLevel: 4, distance: "3.5 km", gradientKey: "restaurants", openingHours: "Wed-Sun · 12:00-22:00", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], tags: ["Garden", "Lunch", "Dinner"], services: MockServices.restaurantMenu, highlights: ["Garden tables", "Special occasions", "Verified"]),
        make(id: "b006", name: "Organikks", tagline: "Fresh cafe plates and wellness bowls", description: "A bright cafe for fresh bowls, smoothies, clean breakfast plates, and quick lunches.", categoryID: "cafes", categoryName: "Cafe", location: .harare, rating: 4.5, reviewCount: 219, priceLevel: 2, distance: "2.1 km", gradientKey: "cafes", openingHours: "Daily · 07:30-17:00", imageNames: ["spotly_sample_cafe_hero", "spotly_sample_cafe_card_1"], tags: ["Breakfast", "Smoothies", "Healthy"], services: MockServices.restaurantMenu, highlights: ["Fresh bowls", "Coffee", "Quick lunch"]),
        make(id: "b007", name: "Court-side Cafe", tagline: "Coffee, brunch, and post-match plates", description: "A cafe built around active mornings, serving coffee, sandwiches, juices, and light plates next to the courts.", categoryID: "cafes", categoryName: "Cafe", location: .avondale, rating: 4.4, reviewCount: 133, priceLevel: 2, distance: "0.9 km", gradientKey: "cafes", openingHours: "Daily · 06:30-19:00", imageNames: ["spotly_sample_cafe_hero", "spotly_sample_cafe_card_1"], tags: ["Coffee", "Brunch", "Padel"], services: MockServices.restaurantMenu, highlights: ["Early coffee", "Healthy plates", "Near courts"]),
        make(id: "b008", name: "Quick Plate Avondale", tagline: "Reliable takeaway for busy days", description: "Fast meals, combos, and delivery-friendly plates for lunch, dinner, and office orders.", categoryID: "takeaways", categoryName: "Takeaway", location: .avondale, rating: 4.3, reviewCount: 91, priceLevel: 1, distance: "1.0 km", gradientKey: "restaurants", openingHours: "Daily · 10:00-22:00", imageNames: ["spotly_sample_restaurant_card_1"], tags: ["Takeaway", "Combos", "Delivery"], services: MockServices.restaurantMenu, highlights: ["Fast pickup", "Family combos", "Delivery ready"]),

        make(id: "b009", name: "Spar Avondale", tagline: "Everyday groceries in Avondale", description: "A dependable neighbourhood supermarket for fresh produce, pantry items, household basics, and quick grocery delivery.", categoryID: "groceries", categoryName: "Groceries", location: .avondale, rating: 4.5, reviewCount: 189, priceLevel: 2, distance: "1.4 km", gradientKey: "groceries", openingHours: "Daily · 07:00-21:00", imageNames: ["spotly_sample_grocery_card_1"], tags: ["Fresh produce", "Bakery", "Household"], services: MockServices.groceryItems, highlights: ["Same-day mock checkout", "Fresh produce", "Household essentials"]),
        make(id: "b010", name: "Spar Borrowdale", tagline: "Premium north-side grocery stop", description: "A polished grocery experience for premium pantry items, deli options, produce, and everyday essentials.", categoryID: "groceries", categoryName: "Groceries", location: .borrowdale, rating: 4.6, reviewCount: 242, priceLevel: 2, distance: "2.4 km", gradientKey: "groceries", openingHours: "Daily · 07:00-21:00", imageNames: ["spotly_sample_grocery_card_1"], tags: ["Deli", "Produce", "Delivery"], services: MockServices.groceryItems, highlights: ["Deli counter", "Fresh bakery", "Verified store"]),
        make(id: "b011", name: "Food Lovers Market Harare", tagline: "Fresh market baskets and deli staples", description: "A larger grocery and fresh market destination with produce, butchery, bakery, deli, and weekly household shopping.", categoryID: "groceries", categoryName: "Groceries", location: .harare, rating: 4.7, reviewCount: 356, priceLevel: 2, distance: "3.7 km", gradientKey: "groceries", openingHours: "Daily · 08:00-20:00", imageNames: ["spotly_sample_grocery_card_1"], tags: ["Market", "Butchery", "Bakery"], services: MockServices.groceryItems, highlights: ["Large produce range", "Butchery", "Bulk baskets"]),
        make(id: "b012", name: "Food Lovers Market Bulawayo", tagline: "Fresh groceries for Bulawayo homes", description: "A market-style grocery stop with a wide range of fresh essentials, household basics, and deli items.", categoryID: "groceries", categoryName: "Groceries", location: .bulawayo, rating: 4.5, reviewCount: 204, priceLevel: 2, distance: "5.1 km", gradientKey: "groceries", openingHours: "Daily · 08:00-20:00", imageNames: ["spotly_sample_grocery_card_1"], tags: ["Bulawayo", "Fresh market", "Pantry"], services: MockServices.groceryItems, highlights: ["City-wide delivery planned", "Fresh essentials", "Market range"]),
        make(id: "b013", name: "Fresh Co Greendale", tagline: "Clean local produce and home basics", description: "A compact Greendale grocer focused on fresh produce, pantry staples, bottled water, and household essentials.", categoryID: "groceries", categoryName: "Groceries", location: .harare, rating: 4.4, reviewCount: 118, priceLevel: 2, distance: "4.6 km", gradientKey: "groceries", openingHours: "Mon-Sat · 08:00-19:00", imageNames: ["spotly_sample_grocery_card_1"], tags: ["Produce", "Greendale", "Essentials"], services: MockServices.groceryItems, highlights: ["Quick baskets", "Neighbourhood store", "Fresh staples"]),

        make(id: "b014", name: "Booties Pharmacy", tagline: "Trusted wellness and pharmacy support", description: "A pharmacy partner for wellness essentials, pharmacist guidance, and prescription verification before in-store collection.", categoryID: "pharmacy", categoryName: "Pharmacy", location: .harare, rating: 4.6, reviewCount: 184, priceLevel: 2, distance: "2.7 km", gradientKey: "pharmacy", openingHours: "Daily · 08:00-20:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Pharmacy", "Wellness", "Verification"], services: MockServices.pharmacyItems, highlights: ["Prescription verification", "In-store collection", "Wellness essentials"]),
        make(id: "b015", name: "Diamond Pharmacy", tagline: "Pharmacy care with quick item requests", description: "A verified pharmacy for general wellness products, first aid items, and regulated prescription verification.", categoryID: "pharmacy", categoryName: "Pharmacy", location: .borrowdale, rating: 4.5, reviewCount: 142, priceLevel: 2, distance: "2.9 km", gradientKey: "pharmacy", openingHours: "Mon-Sat · 08:00-19:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["First aid", "Wellness", "Collection"], services: MockServices.pharmacyItems, highlights: ["Request items", "Verified pharmacy", "Regulated checkout copy"]),
        make(id: "b016", name: "Med Orange Clinic", tagline: "Clinic appointments made simple", description: "A professional clinic offering general consultations, wellness checks, and follow-up appointments through a simple mock booking flow.", categoryID: "doctors", categoryName: "Doctor", location: .harare, rating: 4.7, reviewCount: 126, priceLevel: 2, distance: "3.2 km", gradientKey: "doctors", openingHours: "Mon-Fri · 08:00-17:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Clinic", "Appointments", "Family care"], services: MockServices.doctorServices, highlights: ["Appointment booking", "General consultations", "No medical advice in app"]),
        make(id: "b017", name: "Med Orange Pharmacy", tagline: "Wellness items and verified collection", description: "A pharmacy extension for general items, wellness essentials, and prescription verification before fulfilment.", categoryID: "pharmacy", categoryName: "Pharmacy", location: .harare, rating: 4.4, reviewCount: 98, priceLevel: 2, distance: "3.4 km", gradientKey: "pharmacy", openingHours: "Mon-Sat · 08:00-18:30", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Clinic pharmacy", "Verification"], services: MockServices.pharmacyItems, highlights: ["Prescription verification", "Clinic-adjacent", "Item requests"]),
        make(id: "b018", name: "Borrowdale Family Doctor", tagline: "Family appointments in Borrowdale", description: "A family doctor practice for general appointments, routine checkups, and follow-up consultations.", categoryID: "doctors", categoryName: "Doctor", location: .borrowdale, rating: 4.8, reviewCount: 167, priceLevel: 3, distance: "2.2 km", gradientKey: "doctors", openingHours: "Mon-Fri · 08:00-16:30", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Family doctor", "Consultation"], services: MockServices.doctorServices, highlights: ["Appointment slots", "Family practice", "Verified provider"]),
        make(id: "b019", name: "Avondale Medical Rooms", tagline: "Professional outpatient appointments", description: "Outpatient medical rooms with general consultations and routine wellness checks by appointment.", categoryID: "doctors", categoryName: "Doctor", location: .avondale, rating: 4.5, reviewCount: 83, priceLevel: 2, distance: "1.6 km", gradientKey: "doctors", openingHours: "Mon-Fri · 08:00-17:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Medical rooms", "Consultations"], services: MockServices.doctorServices, highlights: ["Central Avondale", "Follow-ups", "Verified"]),

        make(id: "b020", name: "Bloom & Co Flowers", tagline: "Flowers for thoughtful moments", description: "A polished flower studio for rose bouquets, sympathy flowers, celebration hampers, and custom arrangements.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .borrowdale, rating: 4.7, reviewCount: 92, priceLevel: 2, distance: "2.5 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 08:00-18:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Bouquets", "Hampers", "Delivery"], services: MockServices.flowerGiftItems, highlights: ["Gift notes", "Delivery placeholder", "Custom arrangements"]),
        make(id: "b021", name: "Petal House Harare", tagline: "Elegant bouquets and event stems", description: "A boutique florist creating premium bouquets, ceremony flowers, and same-day gift arrangements.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .harare, rating: 4.6, reviewCount: 77, priceLevel: 2, distance: "3.1 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 08:30-17:30", imageNames: ["spotly_sample_salon_card_1"], tags: ["Florist", "Events", "Gifts"], services: MockServices.flowerGiftItems, highlights: ["Same-day requests", "Event flowers", "Gift delivery"]),
        make(id: "b022", name: "Gifted Zimbabwe", tagline: "Curated gifts and hampers", description: "Gift boxes, celebration hampers, custom notes, and premium local products for thoughtful deliveries.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .harare, rating: 4.5, reviewCount: 64, priceLevel: 2, distance: "2.8 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 09:00-18:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Gift boxes", "Hampers"], services: MockServices.flowerGiftItems, highlights: ["Custom messages", "Curated boxes", "Delivery-ready"]),
        make(id: "b023", name: "Flora Basket", tagline: "Simple flowers, clean delivery", description: "A practical flower and gift store for roses, seasonal stems, sympathy flowers, and quick custom arrangements.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .avondale, rating: 4.3, reviewCount: 58, priceLevel: 2, distance: "1.7 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 08:00-17:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Flowers", "Delivery"], services: MockServices.flowerGiftItems, highlights: ["Fast requests", "Gift notes", "Seasonal stems"]),

        make(id: "b024", name: "Lumiere Beauty Studio", tagline: "Where every detail matters", description: "A premium beauty studio known for hair, nails, makeup, and precise client service in a calm setting.", categoryID: "beauty", categoryName: "Beauty", location: .samLevys, rating: 4.6, reviewCount: 415, priceLevel: 3, distance: "3.1 km", gradientKey: "beauty", openingHours: "Mon-Sat · 08:30-19:00", imageNames: ["spotly_sample_salon_card_1", "spotly_sample_spa_card_1"], tags: ["Hair", "Nails", "Makeup"], services: MockServices.beautyServices, reviews: MockReviews.set2, highlights: ["Book appointment", "Bridal specialists", "Walk-ins welcome"]),
        make(id: "b025", name: "Crown Hair Lounge", tagline: "Modern hair styling and care", description: "A salon for cuts, braids, colour, treatments, and polished everyday styling.", categoryID: "beauty", categoryName: "Beauty", location: .harare, rating: 4.5, reviewCount: 203, priceLevel: 2, distance: "2.0 km", gradientKey: "beauty", openingHours: "Tue-Sat · 08:30-18:30", imageNames: ["spotly_sample_salon_card_1"], tags: ["Hair", "Braids", "Colour"], services: MockServices.beautyServices, reviews: MockReviews.set2, highlights: ["Braids", "Treatments", "Appointment booking"]),
        make(id: "b026", name: "Blush Nail Bar", tagline: "Clean nails and beauty appointments", description: "A compact nail and beauty bar for manicures, pedicures, gel sets, and quick beauty services.", categoryID: "beauty", categoryName: "Beauty", location: .avondale, rating: 4.4, reviewCount: 158, priceLevel: 2, distance: "1.5 km", gradientKey: "beauty", openingHours: "Mon-Sat · 09:00-18:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Nails", "Gel", "Beauty"], services: MockServices.beautyServices, highlights: ["Manicures", "Gel polish", "Quick appointments"]),
        make(id: "b027", name: "Glow Lab Beauty", tagline: "Facials and glow-focused treatments", description: "A beauty studio for facials, skin treatments, nails, and simple appointment-based care.", categoryID: "beauty", categoryName: "Beauty", location: .borrowdale, rating: 4.6, reviewCount: 121, priceLevel: 3, distance: "2.9 km", gradientKey: "beauty", openingHours: "Mon-Sat · 09:00-18:00", imageNames: ["spotly_sample_spa_card_1"], tags: ["Facials", "Skin", "Nails"], services: MockServices.beautyServices, highlights: ["Facials", "Skin care", "Verified"]),

        make(id: "b028", name: "Vertex Wellness Spa", tagline: "Restore, reset, revive", description: "Harare wellness destination for massages, facials, and body treatments in a calm, commercial spa setting.", categoryID: "wellnessSpa", categoryName: "Wellness & Spa", location: .highlands, rating: 4.9, reviewCount: 188, priceLevel: 3, distance: "2.4 km", gradientKey: "wellnessSpa", openingHours: "Mon-Sat · 09:00-20:00", phone: "+263 77 200 0002", isFeatured: true, imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Massage", "Facial", "Gift vouchers"], services: MockServices.spaServices, reviews: MockReviews.set2, highlights: ["Certified therapists", "Couples room", "Gift packages"]),
        make(id: "b029", name: "Daddy Wellness Lounge", tagline: "Calm treatments with a modern edge", description: "A neatly branded wellness lounge offering massage treatments, grooming add-ons, and reset packages for busy professionals.", categoryID: "wellnessSpa", categoryName: "Wellness & Spa", location: .harare, rating: 4.5, reviewCount: 86, priceLevel: 2, distance: "3.0 km", gradientKey: "wellnessSpa", openingHours: "Mon-Sat · 09:00-19:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Massage", "Grooming", "Packages"], services: MockServices.spaServices, reviews: MockReviews.set2, highlights: ["Intentional brand concept", "Treatment packages", "Book online"]),
        make(id: "b030", name: "Highlands Massage Studio", tagline: "Focused massage therapy", description: "A quiet studio for Swedish massage, deep tissue treatments, and simple recovery appointments.", categoryID: "wellnessSpa", categoryName: "Wellness & Spa", location: .highlands, rating: 4.7, reviewCount: 112, priceLevel: 2, distance: "2.6 km", gradientKey: "wellnessSpa", openingHours: "Mon-Sat · 08:00-18:30", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Massage", "Recovery"], services: MockServices.spaServices, reviews: MockReviews.set2, highlights: ["Deep tissue", "Recovery focus", "Verified therapists"]),
        make(id: "b031", name: "Serenity Spa", tagline: "Classic spa days and treatments", description: "A serene spa for facials, massage, couple packages, and half-day treatment plans.", categoryID: "wellnessSpa", categoryName: "Wellness & Spa", location: .borrowdale, rating: 4.6, reviewCount: 139, priceLevel: 3, distance: "3.3 km", gradientKey: "wellnessSpa", openingHours: "Tue-Sun · 09:00-19:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Spa day", "Massage", "Facials"], services: MockServices.spaServices, reviews: MockReviews.set2, highlights: ["Spa packages", "Couples", "Gift vouchers"]),

        make(id: "b032", name: "Court Zero Padel", tagline: "Zimbabwe's premier padel club", description: "Five premium indoor courts, coaching, social play, and tournament-ready facilities for casual and competitive players.", categoryID: "padel", categoryName: "Padel", location: .avondale, rating: 4.7, reviewCount: 246, priceLevel: 2, distance: "0.8 km", gradientKey: "padel", openingHours: "Daily · 06:00-22:00", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Padel", "Coaching", "Tournaments"], services: MockServices.activityServices, highlights: ["Court bookings", "Coaching", "Equipment rental"]),
        make(id: "b033", name: "Wild Is Life Experience", tagline: "A memorable conservation visit", description: "A premium conservation experience with guided encounters, education, and peaceful outdoor time near Harare.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.9, reviewCount: 286, priceLevel: 3, distance: "9.8 km", gradientKey: "activities", openingHours: "Wed-Sun · 10:00-16:00", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Conservation", "Guided", "Family"], services: MockServices.activityServices, highlights: ["Guided slots", "Family friendly", "Weekend plans"]),
        make(id: "b034", name: "Lake Chivero Day Escape", tagline: "A day out near the water", description: "A simple day escape package with lake views, picnic options, activities, and group-friendly slots.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.3, reviewCount: 95, priceLevel: 2, distance: "28 km", gradientKey: "activities", openingHours: "Fri-Sun · 08:00-17:00", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Day trip", "Lake", "Picnic"], services: MockServices.activityServices, highlights: ["Day packages", "Group slots", "Outdoor"]),
        make(id: "b035", name: "Domboshava Sunset Walk", tagline: "Guided sunset walks and views", description: "A guided walking experience for small groups, sunset views, and low-pressure outdoor plans.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.6, reviewCount: 151, priceLevel: 1, distance: "31 km", gradientKey: "activities", openingHours: "Fri-Sun · 15:00-18:30", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Hiking", "Sunset", "Guided"], services: MockServices.activityServices, highlights: ["Sunset slots", "Guide placeholder", "Group booking"]),
        make(id: "b036", name: "Victoria Falls Weekend Stay", tagline: "Weekend stay package by the Falls", description: "A polished staycation placeholder for weekend packages, room options, activity add-ons, and availability requests.", categoryID: "staycations", categoryName: "Staycation", location: .victoriaFalls, rating: 4.8, reviewCount: 304, priceLevel: 4, distance: "Flight", gradientKey: "staycations", openingHours: "Availability by request", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Victoria Falls", "Weekend", "Rooms"], services: MockServices.staycationServices, highlights: ["Check availability", "Room packages", "Activity add-ons"]),
        make(id: "b037", name: "Nyanga Retreat", tagline: "Mountain air and quiet weekends", description: "A calm retreat listing for room packages, couples weekends, and nature-focused stays in Nyanga.", categoryID: "staycations", categoryName: "Staycation", location: .mutare, rating: 4.7, reviewCount: 174, priceLevel: 3, distance: "Road trip", gradientKey: "staycations", openingHours: "Availability by request", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Retreat", "Mountain", "Weekend"], services: MockServices.staycationServices, highlights: ["Weekend packages", "Retreat options", "Availability mock flow"]),
        make(id: "b038", name: "Iron & Ritual Gym", tagline: "Build your best self", description: "A results-driven fitness facility with strength equipment, group classes, and personal training sessions.", categoryID: "gyms", categoryName: "Gym", location: .highlands, rating: 4.4, reviewCount: 198, priceLevel: 2, distance: "2.9 km", gradientKey: "gyms", openingHours: "Mon-Fri · 05:00-22:00", imageNames: ["spotly_sample_gym_card_1"], tags: ["Weights", "Classes", "PT"], services: MockServices.activityServices, highlights: ["Book session", "Group classes", "Personal training"]),
        make(id: "b039", name: "Harare Social Club", tagline: "Late plans, music, and lounges", description: "A nightlife listing for music nights, lounge tables, and weekend plans in central Harare.", categoryID: "nightlife", categoryName: "Nightlife", location: .harare, rating: 4.3, reviewCount: 144, priceLevel: 3, distance: "3.8 km", gradientKey: "nightlife", openingHours: "Thu-Sun · 18:00-late", imageNames: ["spotly_sample_event_hero", "spotly_sample_nightlife_card_1"], tags: ["Lounge", "Music", "Tables"], services: MockServices.restaurantMenu, highlights: ["Table requests", "Weekend plans", "Events"]),
        make(id: "b040", name: "Spotly Launch Offers", tagline: "Early partner deals and bundles", description: "A curated placeholder for launch offers across food, wellness, groceries, and activities.", categoryID: "offers", categoryName: "Offer", location: .harare, rating: 4.5, reviewCount: 60, priceLevel: 1, distance: "Citywide", gradientKey: "offers", openingHours: "Limited launch offers", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], tags: ["Deals", "Launch", "Bundles"], services: MockServices.restaurantMenu, highlights: ["Demo offers", "Partner bundles", "No payment yet"]),
        make(id: "b041", name: "Fresh Kitchen", tagline: "Fresh bowls, grilled plates, and clean lunches", description: "A modern Zimbabwe-oriented casual restaurant for lunch bowls, grilled proteins, salads, and quick dinner orders.", categoryID: "restaurants", categoryName: "Restaurant", location: .harare, rating: 4.5, reviewCount: 154, priceLevel: 2, distance: "2.6 km", gradientKey: "restaurants", openingHours: "Mon-Sat · 10:00-21:00", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], tags: ["Healthy", "Lunch", "Bowls"], services: MockServices.restaurantMenu, highlights: ["Fresh plates", "Office lunches", "Order ahead"]),
        make(id: "b042", name: "La Fontaine Bistro", tagline: "French-inspired bistro dining", description: "A refined bistro for polished dinners, business lunches, desserts, and relaxed wine-led evenings.", categoryID: "restaurants", categoryName: "Restaurant", location: .harare, rating: 4.6, reviewCount: 132, priceLevel: 3, distance: "3.9 km", gradientKey: "restaurants", openingHours: "Tue-Sun · 12:00-22:00", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_2"], tags: ["Bistro", "Wine", "Dinner"], services: MockServices.restaurantMenu, highlights: ["Reserve tables", "Dessert menu", "Date night"]),
        make(id: "b043", name: "Chicken Inn Avondale", tagline: "Fast chicken meals and family combos", description: "A dependable takeaway partner for fried chicken, chips, drinks, and family meal bundles.", categoryID: "takeaways", categoryName: "Takeaway", location: .avondale, rating: 4.2, reviewCount: 418, priceLevel: 1, distance: "1.3 km", gradientKey: "takeaways", openingHours: "Daily · 09:00-22:00", imageNames: ["spotly_sample_restaurant_card_1"], tags: ["Chicken", "Combos", "Fast food"], services: MockServices.restaurantMenu, highlights: ["Quick pickup", "Family combos", "Cash on delivery demo"]),
        make(id: "b044", name: "Pizza Inn Borrowdale", tagline: "Pizza, sides, and group deals", description: "A pizza takeaway for classic pies, family deals, drinks, and delivery-friendly orders.", categoryID: "takeaways", categoryName: "Takeaway", location: .borrowdale, rating: 4.1, reviewCount: 352, priceLevel: 1, distance: "2.0 km", gradientKey: "takeaways", openingHours: "Daily · 10:00-22:00", imageNames: ["spotly_sample_restaurant_card_2"], tags: ["Pizza", "Family", "Delivery"], services: MockServices.restaurantMenu, highlights: ["Pizza deals", "Delivery demo", "Group orders"]),
        make(id: "b045", name: "Nando's Borrowdale", tagline: "Flame-grilled peri-peri favourites", description: "A familiar grilled chicken stop for peri-peri meals, wraps, sides, and takeaway orders.", categoryID: "takeaways", categoryName: "Takeaway", location: .borrowdale, rating: 4.4, reviewCount: 388, priceLevel: 2, distance: "2.2 km", gradientKey: "takeaways", openingHours: "Daily · 10:00-22:00", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], tags: ["Chicken", "Peri-peri", "Takeaway"], services: MockServices.restaurantMenu, highlights: ["Grilled meals", "Pickup", "Delivery-ready"]),
        make(id: "b046", name: "The Burger Yard", tagline: "Stacked burgers and loaded sides", description: "A casual burger spot for smash burgers, loaded chips, shakes, and late lunch orders.", categoryID: "takeaways", categoryName: "Takeaway", location: .harare, rating: 4.3, reviewCount: 119, priceLevel: 2, distance: "3.3 km", gradientKey: "takeaways", openingHours: "Tue-Sun · 11:00-21:30", imageNames: ["spotly_sample_restaurant_card_1"], tags: ["Burgers", "Shakes", "Takeaway"], services: MockServices.restaurantMenu, highlights: ["Smash burgers", "Loaded sides", "Order ahead"]),
        make(id: "b047", name: "Coffee Culture", tagline: "Specialty coffee and quiet work tables", description: "A bright cafe for espresso, pastries, breakfast plates, and focused work sessions.", categoryID: "cafes", categoryName: "Cafe", location: .harare, rating: 4.5, reviewCount: 244, priceLevel: 2, distance: "2.4 km", gradientKey: "cafes", openingHours: "Daily · 07:00-18:00", imageNames: ["spotly_sample_cafe_hero", "spotly_sample_cafe_card_1"], tags: ["Coffee", "Wi-Fi", "Breakfast"], services: MockServices.restaurantMenu, highlights: ["Specialty coffee", "Work-friendly", "Pastries"]),
        make(id: "b048", name: "Veld Cafe", tagline: "Brunch, coffee, and local produce", description: "A relaxed cafe serving brunch plates, seasonal juices, coffee, and light lunches.", categoryID: "cafes", categoryName: "Cafe", location: .newlands, rating: 4.4, reviewCount: 178, priceLevel: 2, distance: "2.7 km", gradientKey: "cafes", openingHours: "Mon-Sat · 07:30-17:00", imageNames: ["spotly_sample_cafe_hero", "spotly_sample_cafe_card_1"], tags: ["Brunch", "Coffee", "Fresh"], services: MockServices.restaurantMenu, highlights: ["Brunch plates", "Fresh juices", "Outdoor seating"]),
        make(id: "b049", name: "Morning Brew", tagline: "Quick coffee and breakfast runs", description: "A compact morning cafe for grab-and-go coffee, breakfast rolls, pastries, and early meetings.", categoryID: "cafes", categoryName: "Cafe", location: .avondale, rating: 4.2, reviewCount: 96, priceLevel: 1, distance: "1.1 km", gradientKey: "cafes", openingHours: "Mon-Fri · 06:30-15:00", imageNames: ["spotly_sample_cafe_card_1"], tags: ["Coffee", "Breakfast", "Grab-and-go"], services: MockServices.restaurantMenu, highlights: ["Fast coffee", "Breakfast rolls", "Office runs"]),
        make(id: "b050", name: "Petal & Bow", tagline: "Modern bouquets and gift notes", description: "A florist and gift studio for bouquets, handwritten notes, celebration boxes, and custom arrangements.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .harare, rating: 4.7, reviewCount: 89, priceLevel: 2, distance: "2.3 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 08:30-18:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Bouquets", "Gift notes", "Delivery"], services: MockServices.flowerGiftItems, highlights: ["Custom notes", "Bouquets", "Delivery demo"]),
        make(id: "b051", name: "Bloom Room", tagline: "Elegant stems and event flowers", description: "A polished flower room for premium stems, event flowers, sympathy arrangements, and curated gifts.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .borrowdale, rating: 4.6, reviewCount: 73, priceLevel: 3, distance: "3.0 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 09:00-17:30", imageNames: ["spotly_sample_salon_card_1"], tags: ["Florist", "Events", "Premium"], services: MockServices.flowerGiftItems, highlights: ["Event flowers", "Premium stems", "Gift hampers"]),
        make(id: "b052", name: "Gift House", tagline: "Curated hampers and celebration boxes", description: "A gifting store for birthdays, corporate hampers, celebration boxes, and custom gift requests.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .avondale, rating: 4.4, reviewCount: 65, priceLevel: 2, distance: "1.9 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 09:00-18:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Hampers", "Birthdays", "Corporate"], services: MockServices.flowerGiftItems, highlights: ["Corporate hampers", "Custom boxes", "Delivery requests"]),
        make(id: "b053", name: "Crown Salon", tagline: "Hair care, braids, and everyday polish", description: "A salon for haircuts, braids, treatments, and practical beauty appointments.", categoryID: "beauty", categoryName: "Beauty", location: .harare, rating: 4.5, reviewCount: 182, priceLevel: 2, distance: "2.5 km", gradientKey: "beauty", openingHours: "Tue-Sat · 08:30-18:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Hair", "Braids", "Salon"], services: MockServices.beautyServices, reviews: MockReviews.set2, highlights: ["Braids", "Hair treatments", "Appointment booking"]),
        make(id: "b054", name: "Glow Bar", tagline: "Skin, nails, and glow appointments", description: "A clean beauty bar for facials, nails, brows, and simple glow-focused treatments.", categoryID: "beauty", categoryName: "Beauty", location: .borrowdale, rating: 4.5, reviewCount: 104, priceLevel: 2, distance: "2.8 km", gradientKey: "beauty", openingHours: "Mon-Sat · 09:00-18:00", imageNames: ["spotly_sample_spa_card_1"], tags: ["Facial", "Nails", "Brows"], services: MockServices.beautyServices, reviews: MockReviews.set2, highlights: ["Facials", "Nails", "Brow care"]),
        make(id: "b055", name: "Daddy Wellness", tagline: "Massage, grooming, and reset sessions", description: "A polished wellness concept offering focused massages, grooming add-ons, and weekday reset packages.", categoryID: "wellnessSpa", categoryName: "Wellness & Spa", location: .avondale, rating: 4.4, reviewCount: 91, priceLevel: 2, distance: "1.7 km", gradientKey: "wellnessSpa", openingHours: "Mon-Sat · 09:00-19:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Massage", "Grooming", "Reset"], services: MockServices.spaServices, reviews: MockReviews.set2, highlights: ["Massage packages", "Grooming add-ons", "Book treatment"]),
        make(id: "b056", name: "Wild Trails", tagline: "Guided outdoor adventures", description: "A guided activity partner for hiking, family walks, team outings, and outdoor weekend plans.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.6, reviewCount: 137, priceLevel: 2, distance: "18 km", gradientKey: "activities", openingHours: "Fri-Sun · 07:00-16:00", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Hiking", "Guided", "Family"], services: MockServices.activityServices, highlights: ["Guided trails", "Group packages", "Family slots"]),
        make(id: "b057", name: "Lakeview Staycation", tagline: "Short stays and day passes by the water", description: "A staycation partner for day passes, weekend stays, lake-view packages, and family-friendly escapes.", categoryID: "staycations", categoryName: "Staycation", location: .harare, rating: 4.5, reviewCount: 122, priceLevel: 3, distance: "24 km", gradientKey: "staycations", openingHours: "Availability by request", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Day pass", "Weekend", "Lake"], services: MockServices.staycationServices, highlights: ["Day passes", "Weekend stays", "Availability requests"]),
        make(id: "b058", name: "Escape Room Harare", tagline: "Team puzzles and indoor challenges", description: "An indoor activity venue for teams, families, birthdays, and puzzle-led group sessions.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.4, reviewCount: 108, priceLevel: 2, distance: "3.6 km", gradientKey: "activities", openingHours: "Wed-Sun · 11:00-21:00", imageNames: ["spotly_sample_padel_card_1"], tags: ["Indoor", "Team", "Family"], services: MockServices.activityServices, highlights: ["Group bookings", "Birthday slots", "Indoor activity"]),
        make(id: "b059", name: "Greenside Grocers", tagline: "Fresh local produce and household essentials", description: "A neighbourhood grocer in Greenside with quality fresh produce, pantry staples, local dairy, and household basics for weekly shopping.", categoryID: "groceries", categoryName: "Groceries", location: .harare, rating: 4.5, reviewCount: 143, priceLevel: 2, distance: "3.2 km", gradientKey: "groceries", openingHours: "Mon-Sat · 07:30-19:30", imageNames: ["spotly_sample_grocery_card_1"], tags: ["Fresh produce", "Local", "Essentials"], services: MockServices.groceryItems, highlights: ["Local sourcing", "Quick baskets", "Neighbourhood store"]),
        make(id: "b060", name: "Daily Basket", tagline: "Your daily grocery delivery partner", description: "A curated delivery-ready grocery store stocking everyday household essentials, fresh produce, snacks, and pantry items for same-day demo ordering.", categoryID: "groceries", categoryName: "Groceries", location: .avondale, rating: 4.3, reviewCount: 87, priceLevel: 2, distance: "2.0 km", gradientKey: "groceries", openingHours: "Daily · 07:00-20:00", imageNames: ["spotly_sample_grocery_card_1"], tags: ["Delivery", "Daily", "Essentials"], services: MockServices.groceryItems, highlights: ["Delivery demo", "Daily staples", "Same-day orders"]),
        make(id: "b061", name: "City Care Pharmacy", tagline: "Pharmacy care in the heart of Harare", description: "A central Harare pharmacy for wellness products, first aid items, pharmacist guidance, and regulated prescription verification before in-store collection.", categoryID: "pharmacy", categoryName: "Pharmacy", location: .harare, rating: 4.6, reviewCount: 167, priceLevel: 2, distance: "1.5 km", gradientKey: "pharmacy", openingHours: "Mon-Sat · 08:00-19:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Pharmacy", "Central", "Wellness"], services: MockServices.pharmacyItems, highlights: ["Central location", "Prescription verification", "Wellness items"]),
        make(id: "b062", name: "Avondale Family Doctor", tagline: "Trusted family appointments in Avondale", description: "A family doctor practice in Avondale offering general consultations, wellness checks, routine screenings, and follow-up appointments by booking.", categoryID: "doctors", categoryName: "Doctor", location: .avondale, rating: 4.7, reviewCount: 121, priceLevel: 2, distance: "1.2 km", gradientKey: "doctors", openingHours: "Mon-Fri · 08:00-16:30", imageNames: ["spotly_sample_spa_hero"], tags: ["Family doctor", "Avondale", "Consultation"], services: MockServices.doctorServices, highlights: ["Appointment booking", "Family practice", "Wellness checks"]),
        make(id: "b063", name: "Morning Cup Cafe", tagline: "The best way to start your day", description: "A welcoming morning cafe for specialty coffee, fresh pastries, breakfast sandwiches, and focused early-day work sessions.", categoryID: "cafes", categoryName: "Cafe", location: .borrowdale, rating: 4.6, reviewCount: 198, priceLevel: 2, distance: "2.3 km", gradientKey: "cafes", openingHours: "Daily · 06:30-14:00", imageNames: ["spotly_sample_cafe_hero", "spotly_sample_cafe_card_1"], tags: ["Coffee", "Breakfast", "Morning"], services: MockServices.restaurantMenu, highlights: ["Specialty coffee", "Pastries", "Work-friendly"]),
        make(id: "b064", name: "Urban Eats", tagline: "Bold flavours, fast service", description: "A modern casual dining spot serving creative bowls, wraps, salads, and grilled plates with an urban edge and quick turnaround for lunch and dinner.", categoryID: "restaurants", categoryName: "Restaurant", location: .harare, rating: 4.4, reviewCount: 132, priceLevel: 2, distance: "2.9 km", gradientKey: "restaurants", openingHours: "Mon-Sat · 10:30-21:30", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], tags: ["Bowls", "Wraps", "Casual"], services: MockServices.restaurantMenu, highlights: ["Creative plates", "Fast service", "Lunch deals"]),
        make(id: "b065", name: "Nando's Harare CBD", tagline: "Peri-peri grills for the city crowd", description: "A central Harare Nando's for flame-grilled peri-peri chicken, sides, wraps, and takeaway or dine-in orders for office and city visits.", categoryID: "takeaways", categoryName: "Takeaway", location: .harare, rating: 4.3, reviewCount: 527, priceLevel: 2, distance: "0.8 km", gradientKey: "takeaways", openingHours: "Daily · 10:00-22:00", imageNames: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], tags: ["Chicken", "Peri-peri", "CBD"], services: MockServices.restaurantMenu, highlights: ["Peri-peri grills", "City-centre location", "Takeaway ready"]),
        make(id: "b066", name: "Petal & Stem", tagline: "Fresh stems for every occasion", description: "A boutique flower studio specialising in seasonal stems, celebration arrangements, bridal bouquets, and thoughtful gift deliveries.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .borrowdale, rating: 4.8, reviewCount: 96, priceLevel: 3, distance: "2.8 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 08:00-18:00", isFeatured: true, imageNames: ["spotly_sample_salon_card_1"], tags: ["Bouquets", "Bridal", "Seasonal"], services: MockServices.flowerGiftItems, highlights: ["Bridal bouquets", "Seasonal stems", "Same-day requests"]),
        make(id: "b067", name: "Gift Corner", tagline: "Thoughtful gifts for every moment", description: "A gift shop for birthday hampers, corporate boxes, celebration kits, custom notes, and locally sourced gift items for delivery or in-store collection.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .harare, rating: 4.4, reviewCount: 73, priceLevel: 2, distance: "2.6 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 09:00-18:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Gifts", "Hampers", "Corporate"], services: MockServices.flowerGiftItems, highlights: ["Gift hampers", "Custom boxes", "Corporate orders"]),
        make(id: "b068", name: "Flora Harare", tagline: "Zimbabwe's favourite floral studio", description: "A premium Harare florist for hand-tied bouquets, corporate flowers, sympathy arrangements, and event stems with same-day delivery options.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .harare, rating: 4.7, reviewCount: 115, priceLevel: 3, distance: "3.4 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 08:00-18:30", imageNames: ["spotly_sample_salon_card_1"], tags: ["Premium", "Events", "Corporate"], services: MockServices.flowerGiftItems, highlights: ["Event flowers", "Same-day delivery", "Premium stems"]),
        make(id: "b069", name: "Glow Studio", tagline: "Skin, brows, and beauty rituals", description: "A focused beauty studio for facials, brow shaping, skin treatments, and targeted glow appointments in a calm environment.", categoryID: "beauty", categoryName: "Beauty", location: .harare, rating: 4.6, reviewCount: 189, priceLevel: 2, distance: "2.1 km", gradientKey: "beauty", openingHours: "Mon-Sat · 09:00-18:30", isFeatured: true, imageNames: ["spotly_sample_spa_card_1"], tags: ["Facials", "Brows", "Skin"], services: MockServices.beautyServices, highlights: ["Facial treatments", "Brow styling", "Appointment booking"]),
        make(id: "b070", name: "The Nail Bar", tagline: "Clean nails, every time", description: "A dedicated nail studio for gel sets, manicures, pedicures, nail art, and quick polish appointments with walk-in and booking options.", categoryID: "beauty", categoryName: "Beauty", location: .samLevys, rating: 4.5, reviewCount: 222, priceLevel: 2, distance: "3.0 km", gradientKey: "beauty", openingHours: "Mon-Sat · 09:00-19:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Nails", "Gel", "Manicure"], services: MockServices.beautyServices, highlights: ["Gel polish", "Nail art", "Walk-ins welcome"]),
        make(id: "b071", name: "Luxe Beauty Room", tagline: "Premium beauty in a private setting", description: "An appointment-only luxury beauty room for lash extensions, brows, nail sets, makeup, and high-end beauty services in a private environment.", categoryID: "beauty", categoryName: "Beauty", location: .highlands, rating: 4.8, reviewCount: 144, priceLevel: 4, distance: "3.7 km", gradientKey: "beauty", openingHours: "Tue-Sat · 09:00-18:00", imageNames: ["spotly_sample_spa_card_1"], tags: ["Luxury", "Lashes", "Private"], services: MockServices.beautyServices, highlights: ["Lash extensions", "Private studio", "Premium services"]),
        make(id: "b072", name: "Reset Massage Studio", tagline: "Deep tissue and recovery massage", description: "A focused massage studio offering deep tissue, sports recovery, Swedish, and chair massages for professionals and athletes.", categoryID: "wellnessSpa", categoryName: "Wellness & Spa", location: .avondale, rating: 4.7, reviewCount: 108, priceLevel: 2, distance: "1.6 km", gradientKey: "wellnessSpa", openingHours: "Mon-Sat · 08:00-19:00", imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Massage", "Recovery", "Deep tissue"], services: MockServices.spaServices, reviews: MockReviews.set2, highlights: ["Deep tissue", "Sports recovery", "Book session"]),
        make(id: "b073", name: "Hillside Picnic Co", tagline: "Curated picnic experiences in Harare", description: "A curated outdoor picnic service with setup, hampers, blankets, and chosen scenic locations for dates, birthdays, and groups.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.6, reviewCount: 91, priceLevel: 2, distance: "8 km", gradientKey: "activities", openingHours: "Fri-Sun · 09:00-17:00", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Picnic", "Outdoor", "Dates"], services: MockServices.activityServices, highlights: ["Scenic setup", "Hamper packages", "Group bookings"]),
        make(id: "b074", name: "Adventure Park Harare", tagline: "Thrills for the whole family", description: "An outdoor adventure park with rope courses, zip lines, team challenges, and family-friendly activity options for weekend day plans.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.5, reviewCount: 174, priceLevel: 2, distance: "12 km", gradientKey: "activities", openingHours: "Sat-Sun · 09:00-17:00", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Family", "Outdoor", "Thrills"], services: MockServices.activityServices, highlights: ["Rope courses", "Family day", "Group packages"]),
        make(id: "b075", name: "Spar Avondale", tagline: "Zimbabwe's trusted neighbourhood supermarket", description: "A well-stocked Spar supermarket in Avondale for fresh produce, meats, bakery, frozen goods, household essentials, and daily grocery runs.", categoryID: "groceries", categoryName: "Groceries", location: .avondale, rating: 4.4, reviewCount: 389, priceLevel: 2, distance: "1.1 km", gradientKey: "groceries", openingHours: "Daily · 07:00-21:00", isFeatured: true, imageNames: ["spotly_sample_grocery_card_1"], tags: ["Supermarket", "Fresh produce", "Essentials"], services: MockServices.groceryItems, highlights: ["Full supermarket", "Butchery", "Bakery"]),
        make(id: "b076", name: "Food Lovers Market Borrowdale", tagline: "Fresh, gourmet, and locally sourced", description: "A premium food market in Borrowdale stocking imported produce, artisan cheeses, a fresh deli counter, sushi platters, and a wide range of international brands.", categoryID: "groceries", categoryName: "Groceries", location: .borrowdale, rating: 4.7, reviewCount: 214, priceLevel: 3, distance: "2.4 km", gradientKey: "groceries", openingHours: "Daily · 07:30-20:30", isFeatured: true, imageNames: ["spotly_sample_grocery_card_1"], tags: ["Gourmet", "Imported", "Deli"], services: MockServices.groceryItems, highlights: ["Artisan produce", "Deli counter", "Gourmet imports"]),
        make(id: "b077", name: "FreshCo Bulawayo", tagline: "Quality groceries in Zimbabwe's second city", description: "A modern grocery store serving Bulawayo with fresh produce, household staples, a butchery, and weekly specials for local families.", categoryID: "groceries", categoryName: "Groceries", location: .bulawayo, rating: 4.3, reviewCount: 127, priceLevel: 2, distance: "42 km", gradientKey: "groceries", openingHours: "Daily · 07:00-20:00", imageNames: ["spotly_sample_grocery_card_1"], tags: ["Bulawayo", "Fresh produce", "Family"], services: MockServices.groceryItems, highlights: ["Family grocery", "Weekly specials", "Fresh butchery"]),
        make(id: "b078", name: "Booties Pharmacy", tagline: "Trusted health and wellness essentials", description: "A well-stocked Harare pharmacy for prescription collection, OTC wellness products, first aid, baby care, vitamins, and pharmacist consultations.", categoryID: "pharmacy", categoryName: "Pharmacy", location: .borrowdale, rating: 4.6, reviewCount: 203, priceLevel: 2, distance: "2.0 km", gradientKey: "pharmacy", openingHours: "Mon-Sat · 08:00-19:30", isFeatured: true, imageNames: ["spotly_sample_spa_card_1"], tags: ["Prescription", "Vitamins", "Baby care"], services: MockServices.pharmacyItems, highlights: ["Prescription collection", "Baby care", "Pharmacist guidance"]),
        make(id: "b079", name: "Diamond Pharmacy", tagline: "Efficient pharmacy care in the CBD", description: "A central CBD pharmacy for rapid prescription verification, over-the-counter medicines, wound care, and wellness supplement items.", categoryID: "pharmacy", categoryName: "Pharmacy", location: .harare, rating: 4.4, reviewCount: 145, priceLevel: 2, distance: "0.9 km", gradientKey: "pharmacy", openingHours: "Mon-Sat · 07:30-18:30", imageNames: ["spotly_sample_spa_card_1"], tags: ["CBD", "Prescription", "Wound care"], services: MockServices.pharmacyItems, highlights: ["CBD location", "Fast service", "OTC medicine"]),
        make(id: "b080", name: "Med Orange Clinic", tagline: "Modern clinic care for families", description: "A private medical clinic offering general consultations, blood tests, wellness screenings, immunisations, and follow-up doctor appointments.", categoryID: "doctors", categoryName: "Doctor", location: .highlands, rating: 4.7, reviewCount: 98, priceLevel: 3, distance: "3.2 km", gradientKey: "doctors", openingHours: "Mon-Fri · 08:00-17:00 · Sat 08:00-13:00", imageNames: ["spotly_sample_spa_hero"], tags: ["Private clinic", "Blood tests", "Screenings"], services: MockServices.doctorServices, highlights: ["Private clinic", "Blood tests", "Weekend slots"]),
        make(id: "b081", name: "Chicken Inn Avondale", tagline: "Zimbabwe's favourite crispy chicken", description: "A local favourite takeaway for crispy fried chicken, chips, burgers, and combo meals. Dine-in, takeaway, and drive-through options available.", categoryID: "takeaways", categoryName: "Takeaway", location: .avondale, rating: 4.2, reviewCount: 641, priceLevel: 1, distance: "1.3 km", gradientKey: "takeaways", openingHours: "Daily · 09:00-22:00", isFeatured: true, imageNames: ["spotly_sample_restaurant_card_1"], tags: ["Chicken", "Fast food", "Combos"], services: MockServices.restaurantMenu, highlights: ["Crispy chicken", "Family combos", "Quick service"]),
        make(id: "b082", name: "Bloom & Bow", tagline: "Curated stems for every story", description: "A boutique florist in Harare crafting seasonal bouquets, bridal arrangements, and bespoke event florals with a modern minimalist style.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .highlands, rating: 4.7, reviewCount: 82, priceLevel: 3, distance: "4.1 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 08:30-17:30", imageNames: ["spotly_sample_salon_card_1"], tags: ["Minimalist", "Bridal", "Bespoke"], services: MockServices.flowerGiftItems, reviews: MockReviews.set2, highlights: ["Bespoke arrangements", "Bridal florals", "Event flowers"]),
        make(id: "b083", name: "Petal House", tagline: "Flowers, gifts, and celebration parcels", description: "A one-stop floral and gift destination for roses, dried arrangements, birthday hampers, corporate gifts, and celebration parcels.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .samLevys, rating: 4.5, reviewCount: 67, priceLevel: 2, distance: "2.9 km", gradientKey: "flowersGifts", openingHours: "Mon-Sat · 08:00-17:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Roses", "Hampers", "Celebration"], services: MockServices.flowerGiftItems, highlights: ["Fresh roses", "Birthday hampers", "Corporate parcels"]),
        make(id: "b084", name: "Gifted Zimbabwe", tagline: "Locally curated gifts for every occasion", description: "A curated gift brand sourcing Zimbabwean-made products, hampers, handcrafted items, and personalised gift boxes for delivery or collection.", categoryID: "flowersGifts", categoryName: "Flowers & Gifts", location: .harare, rating: 4.6, reviewCount: 53, priceLevel: 2, distance: "3.5 km", gradientKey: "flowersGifts", openingHours: "Mon-Fri · 09:00-17:00", imageNames: ["spotly_sample_salon_card_1"], tags: ["Local", "Handcrafted", "Personalised"], services: MockServices.flowerGiftItems, highlights: ["Zimbabwe-made", "Custom boxes", "Personalised gifts"]),
        make(id: "b085", name: "Lumière Beauty Studio", tagline: "Premium beauty with a refined touch", description: "A high-end beauty studio offering precision lash extensions, brow lamination, facials, hair styling, and luxury beauty treatments in a refined setting.", categoryID: "beauty", categoryName: "Beauty", location: .borrowdale, rating: 4.9, reviewCount: 176, priceLevel: 4, distance: "2.6 km", gradientKey: "beauty", openingHours: "Tue-Sat · 09:00-18:00", isFeatured: true, imageNames: ["spotly_sample_spa_card_1"], tags: ["Lashes", "Brow lamination", "Luxury"], services: MockServices.beautyServices, highlights: ["Lash extensions", "Brow lamination", "Premium studio"]),
        make(id: "b086", name: "Glow Salon", tagline: "Hair, colour, and treatments under one roof", description: "A full-service hair salon for cuts, braids, colour treatments, blow-outs, and relaxers for all hair types in a friendly walk-in or booked environment.", categoryID: "beauty", categoryName: "Beauty", location: .avondale, rating: 4.5, reviewCount: 233, priceLevel: 2, distance: "1.4 km", gradientKey: "beauty", openingHours: "Mon-Sat · 08:30-18:30", imageNames: ["spotly_sample_salon_card_1"], tags: ["Hair", "Colour", "Braids"], services: MockServices.beautyServices, highlights: ["All hair types", "Colour specialists", "Walk-ins welcome"]),
        make(id: "b087", name: "Serenity Spa", tagline: "Escape, restore, and breathe again", description: "A full-service wellness spa offering signature packages, facials, body wraps, manicures, pedicures, and quiet lounge access for a complete day reset.", categoryID: "wellnessSpa", categoryName: "Wellness & Spa", location: .highlands, rating: 4.8, reviewCount: 149, priceLevel: 3, distance: "3.8 km", gradientKey: "wellnessSpa", openingHours: "Tue-Sun · 09:00-19:00", isFeatured: true, imageNames: ["spotly_sample_spa_hero", "spotly_sample_spa_card_1"], tags: ["Signature package", "Facial", "Body wrap"], services: MockServices.spaServices, highlights: ["Signature packages", "Quiet lounge", "Full-day spa"]),
        make(id: "b088", name: "Wild Horizons Day Trip", tagline: "Guided day trips into Zimbabwe's wild", description: "A curated day trip operator running guided nature walks, game drives, cultural village visits, and scenic experiences from Harare.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.7, reviewCount: 116, priceLevel: 3, distance: "Various", gradientKey: "activities", openingHours: "Daily · Booking required", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Day trip", "Wildlife", "Guided"], services: MockServices.activityServices, highlights: ["Nature walks", "Game drives", "Cultural tours"]),
        make(id: "b089", name: "Lake Chivero Weekend Stay", tagline: "Weekend escapes by the water", description: "A relaxed waterside lodge at Lake Chivero offering weekend packages, fishing, sunset boat trips, and family-friendly chalets for two-night stays.", categoryID: "staycations", categoryName: "Staycation", location: .harare, rating: 4.6, reviewCount: 88, priceLevel: 3, distance: "30 km", gradientKey: "staycations", openingHours: "Availability by booking", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Lake", "Weekend", "Fishing"], services: MockServices.staycationServices, highlights: ["Waterside chalets", "Fishing packages", "Sunset boat trips"]),
        make(id: "b090", name: "Family Fun Park", tagline: "Rides, play zones, and weekend family plans", description: "An outdoor family entertainment park with rides, jumping castles, go-karts, mini golf, food stalls, and covered picnic areas for full-day family outings.", categoryID: "activities", categoryName: "Activity", location: .harare, rating: 4.4, reviewCount: 302, priceLevel: 2, distance: "8 km", gradientKey: "activities", openingHours: "Fri-Sun · 10:00-18:00", imageNames: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], tags: ["Family", "Rides", "Kids"], services: MockServices.activityServices, highlights: ["Go-karts", "Jumping castles", "Family picnic"])
    ]

    static func byCategory(_ id: String) -> [SpotlyBusiness] {
        switch id {
        case "food": return all.filter { ["restaurants", "cafes", "takeaways"].contains($0.categoryID) }
        case "spa": return all.filter { $0.categoryID == "wellnessSpa" }
        case "salons": return all.filter { $0.categoryID == "beauty" }
        default: return all.filter { $0.categoryID == id }
        }
    }

    static func featured() -> [SpotlyBusiness] { all.filter { $0.isFeatured } }
    static func popular() -> [SpotlyBusiness] { all.sorted { $0.rating > $1.rating } }
}

// MARK: - Events

enum MockEvents {
    private static func makeDate(daysAhead: Int, hour: Int = 19) -> Date {
        Calendar.current.date(byAdding: .day, value: daysAhead, to: Date())
            .flatMap { Calendar.current.date(bySettingHour: hour, minute: 0, second: 0, of: $0) } ?? Date()
    }

    static let all: [SpotlyEvent] = [
        SpotlyEvent(id: "e001", name: "Jazz at The Harare Club", description: "An intimate evening of live jazz, cocktails, and polished garden seating at one of Harare's classic venues.", venue: "The Harare Club", location: .harare, startDate: makeDate(daysAhead: 3), endDate: makeDate(daysAhead: 3, hour: 23), price: 25, currency: "USD", imageURLs: ["spotly_sample_event_hero", "spotly_sample_concert_card_1"], gradientKey: "events", categoryID: "events", attendeeCount: 84, isAvailable: true, tags: ["Jazz", "Live music", "Cocktails"], isFeatured: true),
        SpotlyEvent(id: "e002", name: "Food & Wine Festival", description: "A weekend food market with restaurant pop-ups, wine tasting, live music, and family-friendly daytime sessions.", venue: "Borrowdale Race Course", location: .borrowdale, startDate: makeDate(daysAhead: 10, hour: 12), endDate: makeDate(daysAhead: 10, hour: 21), price: 15, currency: "USD", imageURLs: ["spotly_sample_restaurant_hero", "spotly_sample_restaurant_card_1"], gradientKey: "events", categoryID: "events", attendeeCount: 420, isAvailable: true, tags: ["Food", "Wine", "Festival"], isFeatured: true),
        SpotlyEvent(id: "e003", name: "Padel Pro League", description: "Competitive padel matches, social courts, food stalls, and a lively finals day at Court Zero.", venue: "Court Zero Padel", location: .avondale, startDate: makeDate(daysAhead: 5), endDate: makeDate(daysAhead: 6, hour: 18), price: 10, currency: "USD", imageURLs: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], gradientKey: "padel", categoryID: "events", attendeeCount: 210, isAvailable: true, tags: ["Padel", "Sport", "Live"], isFeatured: true),
        SpotlyEvent(id: "e004", name: "Afrobeats Night", description: "A late-night music event with DJs, table reservations, and a clean ticketing placeholder flow.", venue: "Harare Social Club", location: .harare, startDate: makeDate(daysAhead: 6, hour: 21), endDate: makeDate(daysAhead: 7, hour: 2), price: 12, currency: "USD", imageURLs: ["spotly_sample_event_hero", "spotly_sample_nightlife_card_1"], gradientKey: "nightlife", categoryID: "events", attendeeCount: 260, isAvailable: true, tags: ["Afrobeats", "Nightlife", "DJ"], isFeatured: false),
        SpotlyEvent(id: "e005", name: "Farmers Market Weekend", description: "Fresh produce, baked goods, flowers, and family-friendly vendors for a relaxed weekend shop.", venue: "Newlands Market Lawn", location: .newlands, startDate: makeDate(daysAhead: 2, hour: 9), endDate: makeDate(daysAhead: 2, hour: 15), price: nil, currency: "USD", imageURLs: ["spotly_sample_cafe_hero", "spotly_sample_cafe_card_1"], gradientKey: "groceries", categoryID: "events", attendeeCount: 142, isAvailable: true, tags: ["Market", "Family", "Free entry"], isFeatured: false),
        SpotlyEvent(id: "e006", name: "Startup Networking Night", description: "A practical founder and operator meetup with short talks, open networking, and light refreshments.", venue: "Avondale Business Hub", location: .avondale, startDate: makeDate(daysAhead: 12, hour: 18), endDate: makeDate(daysAhead: 12, hour: 21), price: 8, currency: "USD", imageURLs: ["spotly_sample_event_hero", "spotly_sample_concert_card_1"], gradientKey: "events", categoryID: "events", attendeeCount: 96, isAvailable: true, tags: ["Networking", "Founders", "Business"], isFeatured: false),
        SpotlyEvent(id: "e007", name: "Family Fun Day", description: "A simple outdoor family day with games, food vendors, children activities, and shaded seating.", venue: "Harare Gardens", location: .harare, startDate: makeDate(daysAhead: 14, hour: 10), endDate: makeDate(daysAhead: 14, hour: 16), price: 5, currency: "USD", imageURLs: ["spotly_sample_padel_hero", "spotly_sample_padel_card_1"], gradientKey: "activities", categoryID: "events", attendeeCount: 310, isAvailable: true, tags: ["Family", "Outdoor", "Food"], isFeatured: false),
        SpotlyEvent(id: "e008", name: "Sunday Market", description: "A Sunday community market with food vendors, coffee, flowers, fresh produce, and relaxed live acoustic sets.", venue: "Avondale Market Yard", location: .avondale, startDate: makeDate(daysAhead: 9, hour: 10), endDate: makeDate(daysAhead: 9, hour: 15), price: nil, currency: "USD", imageURLs: ["spotly_sample_cafe_hero", "spotly_sample_cafe_card_1"], gradientKey: "events", categoryID: "events", attendeeCount: 190, isAvailable: true, tags: ["Market", "Sunday", "Food"], isFeatured: false),
        SpotlyEvent(id: "e009", name: "Gospel Night Live", description: "A family-friendly gospel music night with reserved seating, food stalls, and clean ticket reservation flow.", venue: "7 Arts Theatre", location: .avondale, startDate: makeDate(daysAhead: 16, hour: 18), endDate: makeDate(daysAhead: 16, hour: 22), price: 10, currency: "USD", imageURLs: ["spotly_sample_event_hero", "spotly_sample_concert_card_1"], gradientKey: "events", categoryID: "events", attendeeCount: 360, isAvailable: true, tags: ["Gospel", "Live music", "Family"], isFeatured: false)
    ]
}

// MARK: - Bookings

enum MockBookings {
    static let all: [SpotlyBooking] = [
        SpotlyBooking(id: "bk001", businessID: "b028", businessName: "Vertex Wellness Spa", businessCategory: "Wellness & Spa", gradientKey: "wellnessSpa", serviceName: "Swedish massage · 60min", date: Calendar.current.date(byAdding: .day, value: 2, to: Date()) ?? Date(), time: "2:00 PM", duration: 60, price: 45, currency: "USD", status: .confirmed, paymentStatus: .unpaid, notes: nil, createdAt: Date(), location: .highlands, confirmationCode: "SPT-8821"),
        SpotlyBooking(id: "bk002", businessID: "b032", businessName: "Court Zero Padel", businessCategory: "Padel", gradientKey: "padel", serviceName: "Court booking · 1hr", date: Calendar.current.date(byAdding: .day, value: 5, to: Date()) ?? Date(), time: "6:00 PM", duration: 60, price: 18, currency: "USD", status: .confirmed, paymentStatus: .unpaid, notes: "Court 3 preferred", createdAt: Date(), location: .avondale, confirmationCode: "SPT-4432"),
        SpotlyBooking(id: "bk003", businessID: "b001", businessName: "Namaste Harare", businessCategory: "Restaurant", gradientKey: "restaurants", serviceName: "Table reservation · Dinner", date: Calendar.current.date(byAdding: .day, value: 6, to: Date()) ?? Date(), time: "7:30 PM", duration: 90, price: 0, currency: "USD", status: .confirmed, paymentStatus: .unpaid, notes: "Pay at venue", createdAt: Date(), location: .borrowdale, confirmationCode: "SPT-2219"),
        SpotlyBooking(id: "bk004", businessID: "e001", businessName: "Jazz at The Harare Club", businessCategory: "Event", gradientKey: "events", serviceName: "2 tickets · General admission", date: Calendar.current.date(byAdding: .day, value: 3, to: Date()) ?? Date(), time: "7:00 PM", duration: 240, price: 50, currency: "USD", status: .confirmed, paymentStatus: .unpaid, notes: "Mock ticket reservation", createdAt: Date(), location: .harare, confirmationCode: "SPT-7728")
    ]
}
